defaults: &defaults

  # sites hosts
  # session expire seconds
  # admin role account
  URL_HOST: peatio.dev:3000
  URL_SCHEMA: http
  SESSION_EXPIRE: 60
  ADMIN:
    - 'dev@foreseer.co'
    - 'admin@playbtc.com'
  TIMEZONE: 'Seoul'

  REDIS_URL: redis://127.0.0.1:6379

  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_PORT: 587
  SMTP_DOMAIN: amazonaws.com
  SMTP_ADDRESS: email-smtp.us-west-2.amazonaws.com
  SMTP_USERNAME: AKIAIMDLDJXJVHCUW75Q
  SMTP_PASSWORD: AuojwM4Vfehcls/gALCYeDrRlwb894suTwlW0qe623bY
  SMTP_AUTHENTICATION: login # could be plain, login or cram_md5

  SUPPORT_MAIL: admin@playbtc.com
  SYSTEM_MAIL_FROM: admin@playbtc.com
  SYSTEM_MAIL_TO: admin@playbtc.com
  OPERATE_MAIL_TO: admin@playbtc.com

  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: 8080
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # pusher settings
  # --------------------------------------------------------------
  # peatio dependence Pusher (http://pusher.com) service
  # you can change your key for production environment.
  # we support development key and secret
  # uncomment below line only development or test
  #
  PUSHER_APP: 365138
  PUSHER_KEY: 7e50e38a9b1eeae385ef
  PUSHER_SECRET: b70a319725b19758de38
  PUSHER_CLUSTER: ap1

  # PUSHER_APP: YOUR_PUSHER_APP
  # PUSHER_KEY: YOUR_PUSHER_KEY
  # PUSHER_SECRET: YOUR_PUSHER_SECRET
  PUSHER_PORT: 80
  PUSHER_WS_PORT: 80
  PUSHER_WSS_PORT: 443
  PUSHER_ENCRYPTED: true

  # twilio setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  TWILIO_NUMBER: YOUR_TWILIO_NUMBER
  TWILIO_SID: YOUR_TWILIO_SID
  TWILIO_TOKEN: YOUR_TWILIO_TOKEN


  # Third party auth

  # Weibo
  # --------------------------------------------------------------
  WEIBO_AUTH: off # on/off
  WEIBO_KEY: 3820920586
  WEIBO_SECRET: 2d6174dc698e86860c75d75b1e8a01c8

  # chat setting
  # --------------------------------------------------------------
  # Do you want chat feature in your exchange ?
  # send mail to community@peatio.com

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  URL_HOST: dev.playbtc.com
  PUSHER_APP: 365139
  PUSHER_KEY: c28971d0b35926fdb442
  PUSHER_SECRET: 5edf2d98b079e8cc88b1
  PUSHER_CLUSTER: ap1

production:
  <<: *defaults
  URL_HOST: playbtc.com
  REDIS_URL: redis://xcprod-002.440ls3.0001.apn2.cache.amazonaws.com:6379

  PUSHER_APP: 365140
  PUSHER_KEY: 5750ff46500a54b73815
  PUSHER_SECRET: 34b58bdbf911926e270b
  PUSHER_CLUSTER: ap1

  SMTP_PORT: 587
  SMTP_DOMAIN: amazonaws.com
  SMTP_ADDRESS: email-smtp.us-west-2.amazonaws.com
  SMTP_USERNAME: AKIAIMDLDJXJVHCUW75Q
  SMTP_PASSWORD: AuojwM4Vfehcls/gALCYeDrRlwb894suTwlW0qe623bY
  SMTP_AUTHENTICATION: login # could be plain, login or cram_md5