- id: 1
  code: 002
  currency: krw
  deposit: true
  withdraw: true
- id: 2
  code: 003
  currency: krw
  deposit: true
  withdraw: true
- id: 3
  code: 004
  currency: krw
  deposit: true
  withdraw: true
- id: 4
  code: 007
  currency: krw
  deposit: true
  withdraw: true
- id: 5
  code: 011
  currency: krw
  deposit: true
  withdraw: true
- id: 6
  code: 012
  currency: krw
  deposit: true
  withdraw: true
- id: 7
  code: 020
  currency: krw
  deposit: true
  withdraw: true
- id: 8
  code: 023
  currency: krw
  deposit: true
  withdraw: true
- id: 9
  code: 027
  currency: krw
  deposit: true
  withdraw: true
- id: 10
  code: 031
  currency: krw
  deposit: true
  withdraw: true
- id: 11
  code: 032
  currency: krw
  deposit: true
  withdraw: true
- id: 12
  code: 034
  currency: krw
  deposit: true
  withdraw: true
- id: 13
  code: 035
  currency: krw
  deposit: true
  withdraw: true
- id: 14
  code: 037
  currency: krw
  deposit: true
  withdraw: true
- id: 15
  code: 039
  currency: krw
  deposit: true
  withdraw: true
- id: 16
  code: 045
  currency: krw
  deposit: true
  withdraw: true
- id: 17
  code: 048
  currency: krw
  deposit: true
  withdraw: true
- id: 18
  code: 050
  currency: krw
  deposit: true
  withdraw: true
- id: 19
  code: 071
  currency: krw
  deposit: true
  withdraw: true
- id: 20
  code: 081
  currency: krw
  deposit: true
  withdraw: true
- id: 21
  code: 088
  currency: krw
  deposit: true
  withdraw: true
- id: 22
  code: 089
  currency: krw
  deposit: true
  withdraw: true
- id: 23
  code: 090
  currency: krw
  deposit: true
  withdraw: true
