development: &defaults
  adapter: mysql2
  encoding: utf8
  database: xcdev
  username: root
  password:
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: xctest

staging:
  <<: *defaults
  database: xcstg

production:
  <<: *defaults
  database: peatio_production
  host: playbtc-1.cluster-ca58malfauiy.ap-northeast-2.rds.amazonaws.com
  port: 3306
  database: xcprod
  username: playbtc
  password: p1ayBtc$$
