- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: bank
  currency: krw
  sort_order: 2
  bank_accounts:
    -
      bank: '우리은행'
      branch: '강남본점'
      holder: '(주)마이비티씨'
      account: '1005-703-004784'
